CREATE DATABASE userdb;
CREATE DATABASE productdb;
CREATE DATABASE cartdb;
CREATE DATABASE orderdb;
CREATE DATABASE paymentdb;
CREATE DATABASE notificationdb;
CREATE DATABASE wishlistdb;
CREATE DATABASE reviewdb;
