apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DB_HOST: "postgres.postgres.svc.cluster.local"
  DB_PORT: "5432"
  JWT_SECRET: "azure-production-jwt-secret-replace-in-keyvault"
